[package]
name = "clap-i18n-richformatter"
version = "0.3.0"
edition = "2024"
license = "MIT"
description = "Clap rich formatter with i18n support"

[dependencies]
i18n-embed = { git = "https://github.com/elide-tools/cargo-i18n.git", rev = "6ce6bf5deaf9e1f302d0d590a7898faafbfa2c4d", features = ["fluent-system"] }
i18n-embed-fl = { git = "https://github.com/elide-tools/cargo-i18n.git", rev = "6ce6bf5deaf9e1f302d0d590a7898faafbfa2c4d" }
rust-embed = "8"
unic-langid = "0"
clap = "4"
clap-i18n-derive = { version = "0.1.0", path = "clap-i18n-derive", optional = true }

[dev-dependencies]
clap = { version = "4", features = ["derive"] }

[features]
default = ["derive"]
derive = ["dep:clap-i18n-derive"]

[workspace]
members = ["clap-i18n-derive"]
